# -*- coding: utf-8 -*-
{
    'name': 'HR Curriculum Vitae Client',
    'version': '17.0.1.0.0',
    'summary': 'Cliente de Curriculum Vitae',
    'category': 'Human Resources',
    'author': 'BACKOFFICE S.A.S.',
    'maintainer': 'BackOffice',
    'company': 'BackOffice S.A.S.',
    'website': 'https://www.boffice.cloud/',
    'depends': [
        'product',
        'ir_attachment_s3_client',
        'hr_contract',
        'hr_recruitment',
        'hr_employee_extended_client',
        'bo_license_client',
    ],
    'data': [
        'views/hr_academic_area.xml',
        'views/hr_cv_pets.xml',
        'views/hr_cv_employee.xml',
        'views/hr_category_hobbies.xml',
        'views/hr_hobbies.xml',
        'views/hr_cv_hobbies_employee.xml',
        'views/hr_sports.xml',
        'views/hr_cv_sports_employee.xml',
        'views/hr_experience_time_view.xml',
        'views/hr_language.xml',
        'views/hr_cv_language_employee.xml',
        'views/hr_holding.xml',
        'views/hr_cv_holding_employee.xml',
        'views/hr_family_group_category_view.xml',
        'views/hr_family_relationship.xml',
        'views/hr_occupations.xml',
        'views/hr_cv_family_group_employee.xml',
        'views/hr_experience_area.xml',
        'views/hr_external_job_position.xml',
        'views/hr_type_contract.xml',
        'views/hr_cv_laboral_experience.xml',
        'views/hr_academic_institution.xml',
        'views/hr_academic_level.xml',
        'views/hr_cv_academic_studies.xml',
        'views/hr_competition_language.xml',
        'views/hr_competition_level_language.xml',
        'views/hr_cv_personal_reference_employee.xml',
        'views/hr_cv_personal_employee_type.xml',
        'views/hr_employee_view.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
