# -*- coding: utf-8 -*-
{
    'name': 'Hr Employee Extended Client',
    'version': '17.0.1.0.0',
    'summary': 'Cliente de extensión de empleados',
    'category': 'Human Resources',
    'author': 'BACKOFFICE S.A.S.',
    'maintainer': 'BackOffice',
    'company': 'BackOffice S.A.S.',
    'website': 'https://www.boffice.cloud/',
    'depends': [
        'hr_recruitment',
        'hr_payroll',
        'bo_license_client',
    ],
    'data': [
        'data/ir_cron_data.xml',
        'views/animal_type_view.xml',
        'views/animal_race.xml',
        'views/animal_pet.xml',
        'wizard/report_employee_wizard_views.xml',
        'views/hr_employment_relationship_view.xml',
        'views/hr_employee_unity_view.xml',
        'views/hr_employee_zone_view.xml',
        'views/hr_cost_center_view.xml',
        'views/hr_cost_line_view.xml',
        'views/hr_arl_level_view.xml',
        'views/hr_arl_view.xml',
        'views/hr_cotract_type_view.xml',
        'views/hr_employee_view.xml',
        'views/inherited_hr_contract_view.xml',
        'views/report_model_config_view.xml',
        'views/res_config_settings_views.xml',
        'views/hr_job_specialization_view.xml',
        'data/legacy_xmlids.xml',
        'security/ir.model.access.csv',
        'views/inherited_hr_department_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
